name: Trigger on Repository Dispatch

on:
  repository_dispatch:

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v2

    - name: Display event payload
      run: |
        echo "Event name: $GITHUB_EVENT_NAME"
        echo "Payload:"
        cat $GITHUB_EVENT_PATH